#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("len", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("hr", 64, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("t", 64, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("meanhr", 64, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("meanhr_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("tpower", 64, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("tpower_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("stationarity", 64, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("stationarity_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("activity", 64, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("activity_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("acmin_i", 64, hls_in, 7, "ap_ovld", "in_data", 1),
	Port_Property("acmin_o", 64, hls_out, 7, "ap_ovld", "out_data", 1),
	Port_Property("acmin_o_ap_vld", 1, hls_out, 7, "ap_ovld", "out_vld", 1),
	Port_Property("hrmin", 64, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("hrmin_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("stmin", 64, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("stmin_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("tpmin", 64, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("tpmin_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("tmin0", 64, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("tmin0_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
	Port_Property("tmin1", 64, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("tmin1_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "activity_kernel";
